"""initial schema: 4 enum types + disputes table

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-08 00:00:00.000000

Hand-written (not autogenerated). Each enum column references the same
Python ``sa.Enum`` instance so SQLAlchemy's built-in dedup only creates
each Postgres ENUM type once during ``create_table``. ``downgrade`` drops
the ENUM types explicitly because SQLAlchemy does not auto-drop them
when the owning table is dropped.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # One Python Enum instance per Postgres type. Reusing the same instance
    # across multiple columns (gate_1_status + gate_2_status) prevents
    # SQLAlchemy from emitting CREATE TYPE twice for the same type.
    dispute_status_enum = sa.Enum(
        "pending",
        "started",
        "completed",
        name="dispute_status",
    )
    gate_status_enum = sa.Enum(
        "overdue",
        "on_track",
        "completed",
        "not_started",
        name="gate_status",
    )
    dispute_overall_status_enum = sa.Enum(
        "intake",
        "investigating",
        "blocked",
        "complete",
        "at_risk",
        name="dispute_overall_status",
    )
    provisional_credit_status_enum = sa.Enum(
        "not_transferred",
        "transferred",
        "revert",
        name="provisional_credit_status",
    )

    op.create_table(
        "disputes",
        sa.Column("dispute_id", sa.String(), primary_key=True, nullable=False),
        sa.Column(
            "investigation_status",
            dispute_status_enum,
            nullable=False,
            server_default="pending",
        ),
        sa.Column(
            "gate_1_status",
            gate_status_enum,
            nullable=False,
            server_default="on_track",
        ),
        sa.Column(
            "gate_2_status",
            gate_status_enum,
            nullable=False,
            server_default="not_started",
        ),
        sa.Column("investigation_deadline", sa.Integer(), nullable=True),
        sa.Column(
            "provisional_credit_status",
            provisional_credit_status_enum,
            nullable=False,
            server_default="not_transferred",
        ),
        sa.Column(
            "provisional_credit_generated",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "deadline_extended",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "status",
            dispute_overall_status_enum,
            nullable=False,
            server_default="intake",
        ),
        sa.Column("user_written_notice", sa.String(), nullable=True),
        sa.Column("written_notice_deadline", sa.Integer(), nullable=True),
        sa.Column("credit_revert_notice_deadline", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )


def downgrade() -> None:
    op.drop_table("disputes")
    # Drop enum types after the table that depends on them is gone.
    for type_name in (
        "provisional_credit_status",
        "dispute_overall_status",
        "gate_status",
        "dispute_status",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {type_name}"))
